### ISSUE TITLE
Sentinel deployment changes for Mainnet

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel#101]
Capture the eventual work which falls out of the deployment changes needed in time for main net.

## Objectives
- Empower Sentinel team to directly manage infrastructure in production/staging
- Make development and staging environments more closely resemble production
- Develop Sentinel-specific tooling for turn-key deployments onto multiple networks
- Creating a more cohesive management of logging/metrics (which can still be exposed and consumed by upstream business/infra concerns)

**Comment by olizilla** [comment]
The current plan for this is to crete a helm chart of Lotus + Visor + Drone so we can run them in k8s. Visor & Drone will write to a hosted Timescaledb and Grafana will query that db (or more likely, a read-only replica of it)

The helm chart will include the option to deploy a local TimescaleDB as part of the cluster to simplify CI and developer set-ups.

Work on that helm chat is happening over here https://github.com/filecoin-project/sentinel-helm-chart (🔒 currently a private repo, sorry)
