### ISSUE TITLE
Express TimescaleDB metrics via Prometheus

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel#104]
In order to capture information about production/staging/dev database instances for awareness and troubleshooting, we will express metrics via prom from Timescale cloud into Grafana.

See https://docs.timescale.com/latest/tutorials/tutorial-setting-up-timescale-cloud-endpoint-for-prometheus

Acceptance Criteria TBD

**Comment by iand** [comment]
Issue moved to [filecoin-project/sentinel-infra #58](https://github.com/filecoin-project/sentinel-infra/issues/58) via [**ZenHub**](https://www.zenhub.com/)
