### ISSUE TITLE
Docker image for lotus

### ISSUE THREAD

**Issue by olizilla** [filecoin-project/sentinel#121]
If we're going full k8s on this, we'll need a blessed docker image for lotus. Even if we don't, it would simplify our set up to all be talking about a tagged image rather than require everyone to build there own.

So far we have
- @ognots minimal flavour - https://github.com/ognots/lotus-docker
  - is that image published?
- openworklabs flavour - https://github.com/openworklabs/filecoin-docker - looks like this was the source for @ognots stripped down version. 
- multiple examples from the lotus repo https://github.com/filecoin-project/lotus/tree/d124d10f7c9542d80bcecdf427c78b25f449f3e7/tools/dockers/docker-examples

The suggestion from the planning meeting was to use ognots one – @ognots can you comment on the reason for the diff on between yours and the openworklabs one? Would be good to be able to trace the image to a repo, and have it built from CI.

### Acceptance Criteria

- An image blessed by the lotus team for authenticity, reliability

**Comment by olizilla** [comment]
looks like openworklabs flavour is currently preferred.

**Comment by placer14** [comment]
Probably worth keeping this open to eventually source a filecoin-project sourced build?

**Comment by placer14** [comment]
Open question on whether collbaorator-provided images might be suitable vs one published by the filecoin project. @ribasushi will investigate latest state of this discussion.

**Comment by placer14** [comment]
Reports from Riba suggest this is indirectly being solved by custom images and collaborator charts. Sentinel is not directly requiring any official releases (since we are exploring custom lotus builds for faster ingestion) here so this is going to be closed as resolved.

**Comment by placer14** [comment]
Tracking issue in https://github.com/filecoin-project/lotus/issues/5311
