### ISSUE TITLE
Sentinel Deploy: Publish Custom Telegraf Docker Image

### ISSUE THREAD

**Issue by ognots** [filecoin-project/sentinel#123]
In order to capture custom Telegraf deployable for k8s, we need to prepare https://github.com/filecoin-shipyard/telegraf-lotus/ as a built docker image.

- [x] Create a repository in Dockerhub
- [x] Create or modify Dockerfile to build image
- [x] Build and Publish docker image manually
- [x] Stretch Goal: build and publish docker image in CI

**Comment by olizilla** [comment]
I can take this on while you sleep! @placer14 can you add me (@olizilla) as an admin to that repo?

**Comment by olizilla** [comment]
Very relevant https://www.influxdata.com/blog/bring-your-own-telegraf/

- tool and guide to publishing your own telegraf image with just the plugins you need!

**Comment by olizilla** [comment]
Alas it seems to not be maintained, but I can harvest ideas from it https://github.com/rawkode/bring-your-own-telegraf

**Comment by olizilla** [comment]
The original circle ci config https://github.com/filecoin-shipyard/telegraf-lotus/blob/c803f0a988cf655ae79be312d34d2928144a0089/.circleci/config.yml

**Comment by olizilla** [comment]
the list of what changed in telegraf-lotus since it was forked from telegraf https://github.com/filecoin-shipyard/telegraf-lotus/compare/c803f0a988cf655ae79be312d34d2928144a0089...6495557

**Comment by olizilla** [comment]
looks like we could avoid forking telegraf and just publish the custom plugins, and then create a docker image for telegraf + 

- plugins/inputs/lotus
- plugins/processors/lotus_peer_id
- plugins/outputs/postgresql

**Comment by olizilla** [comment]
Ah ha! the telegraf config we'd want in the docker image lives in the sentinel repo https://github.com/filecoin-project/sentinel/blob/master/scripts/telegraf.conf.default

**Comment by olizilla** [comment]
This image should live in a docker repo called `filecoin-shipyard/telegraf-lotus`, but the filecoin-shipyard org does not exists on dockerhub yet. I can create it, but would like at least an ACK before adding to the filecoin surface area.

**Comment by olizilla** [comment]
When do the placeholder values in the `scripts/telegraf.conf.default` file get replaced? I see that telegraf config supports [`${ENV_VAR}` style replacements](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#environment-variables) already, but we're using mustach style placeholders `{{ some_var }}`

- https://github.com/filecoin-project/sentinel/blob/d9ab9e767645ee97c687af0ae49c1d4bbddde1de/scripts/telegraf.conf.default#L1-L5
- https://github.com/filecoin-project/sentinel/blob/d9ab9e767645ee97c687af0ae49c1d4bbddde1de/scripts/telegraf.conf.default#L149-L150
- https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#environment-variables

**Comment by olizilla** [comment]
...as we are moving towards k8s, I think those vars will want to be set from the env anyway, so I'm gonna flip them to be `${ENV_VAR}` style.

**Comment by placer14** [comment]
@olizilla As discussed, I'm going to make a quick switch of this repo to the new namespace we decided on today. Also, we decided that the compilation requirements around custom plugins necessitate the continued use of this fork. Though I think there are ways we can reduce the details between this and the upstream repo. But the short term impact is that the repo must stay. I've invited you to this repo, hopefully that sticks through the migrations.

**Comment by olizilla** [comment]
We have a working docker build over in https://github.com/filecoin-project/sentinel-drone/pull/25 - running `make docker-image` in that branch will build a `sentinel-drone` docker image. Until I can push the image to the `filecoin` org on dockerhub a preview lives at `olizilla/sentinel-drone` - https://registry.hub.docker.com/r/olizilla/sentinel-drone

```console
$ make docker-image 
docker build -t "sentinel-drone" .
...
Successfully built 433dfaeccae2
Successfully tagged sentinel-drone:latest
docker tag "sentinel-drone:latest" "sentinel-drone:66a7495e"
$ docker run -it --rm sentinel-drone
2020-09-11T16:56:31Z I! Starting Telegraf 
2020-09-11T16:56:31Z I! Using config file: /etc/telegraf/telegraf.conf
```

next up i need to test it with

TODO:
- [ ] get permissions to publish to `filecoin` org on dockerhub
- [ ] push image
- [ ] test with telegraf helm chart
- [ ] build and publish docker image from CI

**Comment by olizilla** [comment]
Image is now available at `filecoin/sentinel-drone:latest`

**Comment by olizilla** [comment]
YAS, now CI is picking up actual issues!

```
make check

[ERROR] gofmt has found errors in the following files:
plugins/outputs/postgresql/postgresql_test.go plugins/processors/lotus_peer_id/peerid_test.go

Run make fmt to fix them.
make: *** [Makefile:88: fmtcheck] Error 1

Exited with code exit status 2

CircleCI received exit code 2
```

**Comment by olizilla** [comment]
Ok, i fixed the boring issues, and we are now left with... a test failure from our code!

```
--- FAIL: TestTagMetricWithPeerID (0.00s)
    assert.go:15: /go/src/github.com/influxdata/telegraf/plugins/processors/lotus_peer_id/peerid_test.go:40
    assert.go:24: ! ["lotus_peer_id"]: "12D3KooWRHNnsJmKEsJwqxesunwuQXS4V7n74PoK6Ca5NJ87bUcu" != (missing)
    assert.go:24: ! ["peer_id"]: (missing) != "12D3KooWRHNnsJmKEsJwqxesunwuQXS4V7n74PoK6Ca5NJ87bUcu"
FAIL
```

**Comment by iand** [comment]
> Ok, i fixed the boring issues, and we are now left with... a test failure from our code!
> 
> ```
> --- FAIL: TestTagMetricWithPeerID (0.00s)
>     assert.go:15: /go/src/github.com/influxdata/telegraf/plugins/processors/lotus_peer_id/peerid_test.go:40
>     assert.go:24: ! ["lotus_peer_id"]: "12D3KooWRHNnsJmKEsJwqxesunwuQXS4V7n74PoK6Ca5NJ87bUcu" != (missing)
>     assert.go:24: ! ["peer_id"]: (missing) != "12D3KooWRHNnsJmKEsJwqxesunwuQXS4V7n74PoK6Ca5NJ87bUcu"
> FAIL
> ```

Pretty sure that test is wrong because we add the `peer_id` tag, but the test is expecting `lotus_peer_id`

**Comment by olizilla** [comment]
@iand yep! Will fix that in PR. Want to get that CI run green!

**Comment by iand** [comment]
ok, I have a PR to fix here https://github.com/filecoin-project/sentinel-drone/pull/28. Feel free to use it or pull into yours

**Comment by olizilla** [comment]
Great, i'll get CI otherwise working in the PR, and we can have filecoin-project/sentinel-drone#28 turn things green!

**Comment by olizilla** [comment]
There are other test failures in existing plugin tests, so I'm updating the make target to only run go test on our plugins.
