### ISSUE TITLE
meta: remove github integration from #fil-sentinel

### ISSUE THREAD

**Issue by olizilla** [filecoin-project/sentinel#128]
Having github activity in a slack channel makes it harder to pick out conversation. I suggest we disable it. If anyone needs that stream of info, it can be got from github directly. If folks like it in slack then we could direct it to a dedicated channel e.g `#fil-sentinel-activity`

A quick temp check in #fil-sentinel had 4 mildly negative responses to having the github integration in the channel
https://filecoinproject.slack.com/archives/C0174P5M11T/p1599663653058600?thread_ts=1599663577.058500&cid=C0174P5M11T

**Comment by placer14** [comment]
I do like keeping the slack presence, but I'm good with removing it from #fil-sentinel and putting it in #fil-sentinel-activity. 🤝

**Comment by olizilla** [comment]
@andyschwab can you help us make our slacks nice?

**Comment by andyschwab** [comment]
Indeed! #fil-sentinel-activity is up and running, and the integration should be off in #fil-sentinel and on in #fil-sentinel-activity

For reference, does Slack allow you to use any of the GitHub App commands (https://slack.github.com/), or do you get a "no permissions" error?

**Comment by placer14** [comment]
@andyschwab @olizilla The subscribe features seem to work! Love that they can be controlled by feature. Inline issue/PR interactions are icing. Thanks for this!

**Comment by placer14** [comment]
This is completed with activity now in #fil-sentinel-activity on public Filecoin slack.
