### ISSUE TITLE
make run-lotus  报错

### ISSUE THREAD

**Issue by gitseen** [filecoin-project/sentinel#133]
make -C lotus/ deps lotus
make[1]: Entering directory '/root/sentinel/lotus'
make[1]: Nothing to be done for 'deps'.
rm -f lotus
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.232cc320" -o lotus ./cmd/lotus
# pkg-config --cflags  -- /root/sentinel/lotus/extern/filecoin-ffi/generated/../filcrypto.pc /root/sentinel/lotus/extern/filecoin-ffi/generated/../filcrypto.pc /root/sentinel/lotus/extern/filecoin-ffi/generated/../filcrypto.pc /root/sentinel/lotus/extern/filecoin-ffi/generated/../filcrypto.pc /root/sentinel/lotus/extern/filecoin-ffi/generated/../filcrypto.pc
pkg-config: exec: "pkg-config": executable file not found in $PATH
make[1]: *** [Makefile:68: lotus] Error 2
make[1]: Leaving directory '/root/sentinel/lotus'
make: *** [Makefile:33: build/lotus] Error 2

**Comment by olizilla** [comment]
Install `pkg-config`. 

`pkg-config` must be installed and available on your system `$PATH`. See: https://github.com/filecoin-project/lotus/blob/master/documentation/en/install-lotus-ubuntu.md#ubuntu-instructions

`pkg-config` is required to build `lotus` and sentinel uses a `lotus` node to get metrics for the filecoin chain.

**Comment by olizilla** [comment]
If installing `pkg-config` does not solve it, feel free to re-open this issue.
