### ISSUE TITLE
Makefile: "check-sudo" checks for a user named "root", not superuser privileges

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/sentinel#134]
> .PHONY: check-sudo
> check-sudo:
> 	@runner=`whoami` ; \
> 	if [ $$runner != "root" ]; then \
> 		echo "Please run 'make $(MAKECMDGOALS)' with superuser privledges."; \
> 		exit 1; \

This will in no way guarantee what it is intended to guarantee. The root account can be renamed at will. Better check for the UID == 0, via `id` or some other way.

And "priviledge" seems to be obsolete the internet tells me :D

**Comment by PatrickDeuse** [comment]
maybe even better/cleaner: 

check if we have the right privileges on the dir we want to write to instead of a general superuser privileges check.

but the priority of this is so low - use it as an excuse when your boss wants to give you more, new work...

**Comment by placer14** [comment]
Mea culpa. Thanks for capturing this necessary improvement.
