### ISSUE TITLE
Create base view for epoch-centric queries

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/sentinel#136]
Example query that outputs the needed data for this view
```sql
    select distinct on (height) height,
                                time_bucket('30s', to_timestamp(blocks.timestamp)) as "time",
                                parentstateroot
    from blocks
    group by height, timestamp, parentstateroot, parentweight
    order by height desc, parentweight desc
```

This produces a table with a single row per height with values only from the heaviest chain as determined by ordering by `parentweight desc`. I have confirmed that it does output the correct list of parentstateroots using the following query
```sql
with epoch as (
    select height,
           time_bucket('30s', to_timestamp(blocks.timestamp)) as "time",
           parentstateroot,
           cid
    from blocks
    group by height, timestamp, parentstateroot, parentweight, cid
    order by height desc, parentweight desc
)
select distinct on (height) height, parentstateroot, string_agg(cid, ',') as "tipset"
from epoch
group by height, parentstateroot
order by height desc;
```
and then using lotus to compute the stateroot from the output `tipset`s, i.e.
```
$ lotus state --tipset=<copy list from a row in the tipset column> compute-state
```
the output cid should match the parentstateroot of the row above, i.e. the child epoch.

![Screen Shot 2020-09-15 at 10.51.40.png](https://images.zenhubusercontent.com/55b4be994f7a08fbb7f3e816/12609e58-4632-44ae-b293-e5be86dcce19)

```
$ lotus state --tipset=bafy2bzacedlld6vt3aklmobrr6qbfcuk5byapyoqckq7u2hf72yhg2eegkvck compute-state
computed state cid:  bafy2bzaceavadg6i6w772otbtxpq4xgiyonf4u3posorvkvveoisos6kzt3ow
```

**Comment by lanzafame** [comment]
It may be better to remove the `distinct on (height)` from the view query and make it the responsibility of the caller to do that as it makes the view more flexible as seen by the confirmation query ;)

**Comment by placer14** [comment]
Short discussion suggests we might create a new repo which manages the view deployment lifecycle. @placer14 to create a design for further discussion
