### ISSUE TITLE
Visor Chainwatch Docker Image

### ISSUE THREAD

**Issue by ognots** [filecoin-project/sentinel#141]
- [x] Create a Docker image file for github.com/filecoin-project/sentinel-visor
- [x] Create a Dockerhub repo to publish it to hub.docker.com/r/filecoin/sentinel-visor

**Comment by olizilla** [comment]
Dockerfile is made and image is pushed to docekr hub.

but our dockerhub builds are failing, as dockerhub can't deal with git submodules! see https://hub.docker.com/repository/registry-1.docker.io/filecoin/sentinel-visor/builds/c5ed6b06-abbc-4eb1-a215-93c0485396d4

The inernet proposed a a fix to use dockerhub hooks, but they are gross, and, it doesn't fix the problem in our case, so I am switching to pushing images to docker hub from circleci

**Comment by olizilla** [comment]
@ognots as part of the work to push docker images to dockerhub from circleci, could you create a `dockerhub` secrets context for the `filecoin-project` org in circle that I can summon as part of the build? Access to those creds should be limited to builds triggered by a team of blessed folks... anyone who might merge PRs on sentinel repos would need to be part of that team
