### ISSUE TITLE
meta: define our PR review policy for sentinel

### ISSUE THREAD

**Issue by olizilla** [filecoin-project/sentinel#146]
Let's define our defaults for PR reviewing and merging, to make it easier to know what to expect. 

As a starter, assuming we have CI in place I'd suggest

- All checks pass.
- ~~2~~ 1 positive review from a fil-infra team member.
- PR author self-merges when those criteria are met.

We can ecode the first to as branch restrictions on the default branch of each repo. We can leave the escape hatch open that allows repo Admins to override the restricitons, as it's presented as an explict checkbox in the github UI, so there is a small ceremony to knowlingly jumping over the fence.

Alternatively, we could make nominate a codeowner for each sentinel repo while things are in flux, and ensure that all PRs are signed off by the code owner.

The intention here is to ship things faster as we know the rules rather than bog us down with process. I'll do the admin of setting up what ever we decide on.

Thoughts?

**Comment by iand** [comment]
Happy with the bulleted list of suggestions, except I think we only need one reviewer given the size of our team.

**Comment by olizilla** [comment]
Agreed. Edited the proposal to call for 1 rather than 2 reviews

**Comment by placer14** [comment]
Overall these rules sound like a good start. Maybe with the implicit recommendation that a review should not be left if the reviewer does not understand the full impact of the change and if there's a specific person who is KNOWN to understand the full impact, that the PR opener will request their review when submitted. I think having code owners signing off on specific parts of code can be considered later on if we find there are too many moving parts to keep track of all the flowing work.

**Comment by iand** [comment]
We could capture these in a team process document but since we are already following the suggestions I don't see a pressing need to create that at the moment.
