### ISSUE TITLE
Compare Sentinel database's last synced block parent state root if present to source

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel#148]
To protect against the possibile scenario of running chainwatch against different networks and ingesting into the same database, we should check the last block's parent state root against the source node and fatally exit with a warning. The warning may be bypassed with a flag (which should be required each time the node changes to a new network).

**Comment by placer14** [comment]
Or, and here's a crazy thought, we design our schema to support MULTIPLE NETWORKS! 💣 💥

**Comment by iand** [comment]
This applies for both visor and drone. They could be misconfigured to write to the wrong database. This may not matter if we have a way of extracting the consensus chain to a separate schema. 

An alternate design that might be faster to implement and query is to store genesis block hash in the database and compare that when visor/drone first connects.
