### ISSUE TITLE
Explore room for PromConnector to support PromQL in Grafana

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel#150]
Focus on answering the following questions:
- [ ] Can Prom Connector query tables that it didn't create/manage?
- [ ] If so, are there any requirements for schema which supports PromQL queries through Prom Connector?

**Comment by iand** [comment]
I think prom connector here is referring to a component in Timescale's Promscale software. I don't think that can query arbitrary schemas and the PromQL implementation is tied to the specific schema used by promscale. This isn't going to be able to support general promql querying against our data.
