### ISSUE TITLE
Manually scale up historical on-chain processing for future analysis

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel#163]
In order to have a complete historical view of on-chain state, we will scale up a cluster of visor nodes with static Lotus datastores to backfill this state in Sentinel. This issue captures the work required to deliver a database with historical state ingested for analysis.

TODO
- [x] Explore static datastore access optimizations _(using repo lens ingestion)_
- [x] Setup ingestion template for scaling
- [x] Configure snapshot and fast restore in AWS
- [x] Create initial scale deployment (5 nodes?) then scale up to 20
  - some priority on `storageminer` actor processing.. a few nodes to focus solely on this
- [x] Setup monitoring on scaled ingestion setup (for progress and time to completion insight)
- [ ] Setup chainhead indexer to keep up with Network in tandem with historical processing
- [ ] Upon completion of historical backfill, promote database to production
- [ ] Scale down unnecessary nodes needed for backfill

**Comment by placer14** [comment]
Update: Deployed several instances and running processing on each overnight. Scaling up did not get quite as big as I expected...seeing contention particularly on our actors processing table (which manages work queues). Still thinking through what would speed this up as the bottleneck is primarily in updating the processing table with results. Unsure if multiple dimensions of partitioning will help much, but the next obvious dimension would be across actor types.

Observations:
- tipset indexing and message processing took practically no time to process. Was done in less than an hour. Full data on this is already available.
- message params parsing could not be completed in the above batch. blocked on https://github.com/filecoin-project/sentinel-visor/issues/129. Prioritizing fixes here.
- reading directly from the on-disk store (using "repo lens") and avoiding the lotus API is working VERY well. No errors appear to be coming out of it.
- As a result of the repo lens work, I'm seeing an upper bound of about 6k iops (using reserved capacity) around the actorstatechange processor. actorstatechange processor (which identifies which actor states have changed from one tipset to the next to setup work for actor processing) has completed about 60% of the chain within about 4 hours of runtime full throttle on 1 instance. :handshake: :penguin-dance:
- processing stats is very useful (but doesn't need to be running on more than 1 instance for the whole setup.) :sanchez-school-not-a-place-for-smart-people:

There were a few snags from the overnight execution:
- another deadlock found in actor processing. (reopened https://github.com/filecoin-project/sentinel-visor/issues/91 and generalized for all deadlocks to track trends here)
- interrupting visor causing pg connections to hang forces me to remove locks manually while tweaking visor settings
- AWS is _very_ sensitive to anything being in the wrong place while starting new instances. Lost much time trying to understand AWS failures which result in `Server.InternalError: Internal error on launch` and nothing more. :crying_cat_face:
- actor processing is just slow... might need to break this up into smaller processors? If we add partitioning on the actor type dimension, this change seems like an obvious follow-on.

**Comment by iand** [comment]
Closing this now since 99% of backfilling is complete and we are planning ongoing catchups for actor data
