### ISSUE TITLE
historical_scale_pool prevents SQL clients from connecting to analysis db

### ISSUE THREAD

**Issue by olizilla** [filecoin-project/sentinel#169]
The `historical_scale_pool` on the analysis db causes errors when connecting from several db clients. Trying to use the db `mainnet_historical_analysis` directly does not work either. Clients that struggle with it that we know of so far are:

- pgAdmin
- DataGrip
- Observerable

Not being able to connect from Observable is a problem, as it means folks will try and use the monitoring db for ad-hoc queries. I think we want folks to use the analysis db for that, but the configuration prevents it. 

We should configure the analysis db in such a way that popular db clients and Observabel can connect without error.

Client known to work with `historical_scale_pool`

- TablePlus

### Observable

Using the **analysis** db
<img width="835" alt="Screenshot 2020-11-03 at 13 47 45" src="https://user-images.githubusercontent.com/58871/97992988-64bbba80-1ddb-11eb-96eb-4d0d0102a6f5.png">

Using the **monitoring** db
<img width="781" alt="Screenshot 2020-11-03 at 13 40 56" src="https://user-images.githubusercontent.com/58871/97993099-82891f80-1ddb-11eb-8333-192e437a5061.png">

### DataGrip
<img width="363" alt="Screenshot 2020-11-03 at 13 52 30" src="https://user-images.githubusercontent.com/58871/97993348-d8f65e00-1ddb-11eb-8390-283c7f7e6646.png">

**Comment by placer14** [comment]
@olizilla I noticed you tried with the database directly `mainnet_historical_analysis` but the DB uses a different port from the pool. Could you try the DB port (`13573`) with the DB name directly?

**Comment by hsanjuan** [comment]
I have tested and tools seem to be much happier if the pool name matches the database name.

Pools can be easily renamed, but what are the consequences of renaming those pools? What tooling will it break?

We can also create additional pools keeping the old names, but we will need to reduce the pool sizes of the legacy ones so that we can give the slots to the new ones.

**Comment by olizilla** [comment]
- using the same name for the pool and the db made DataGrip happy but not Observable
- accessing the `mainnet_historical_analysis` db directly via port `13573` makes Observable happy. I have added it as a data source to the PL Observable team under the name `sentinel-analysis`

**Comment by iand** [comment]
Closing due to workaround described in last comment
