### ISSUE TITLE
Panel: Gas Burned over Time

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel#170]
In order to track gas outputs over time, we will track the burned gas over time based on data produced by Visor's GasOutputsProcessor.

### Acceptance Criteria
- [x] Gas Burned over time
- [ ] Rolling average over prior 2hrs

**Comment by placer14** [comment]
New requests:
- a rate of change (rolling few hours)
- one more: a cumulative view for burned fil? (will just keep going up, like storage power)
- for the rate of change (rolling few hours) that anorth proposed, could we also get rate over all time? so basically, one line (the rolling one anorth proposed) would shows us the recent rate, and the "over all time" line would be very flat, but show us a baseline to compare current rate against. it would also let us aggregate over longer periods of time to make claims over coming weeks/months
- denomination in FIL, not aFIL

**Comment by placer14** [comment]
Note: "Over all time" will not be possible until all chain data is captured for analysis.

**Comment by placer14** [comment]
We track quite a bit of data in other dashboards which don't require this work to be as high-priority. De-prioritizing. @hsanjuan to see about updating existing panels (and potentially adding rate as requested.)

**Comment by hsanjuan** [comment]
Done by tracking burn account actor balance.
