### ISSUE TITLE
Alert: Parent Base Fee

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel#171]
In order to be notified when Parent Base Fee is high, add an alert to the Main Dashboard's Parent Base Fee panel to trigger when prior 30m avg is greater than 1e5 for longer than 10m.

### Acceptance Criteria
- [x] Apply alert threshold which triggers when prior 30m avg is >1e5 for at least 10m
- [ ] Include actionables for response (needs definition)

**Comment by placer14** [comment]
Looking for actionables which should be pursued once this alert is triggered. /cc @daviddias

**Comment by nonsense** [comment]
As for the current alert threshold: there have been a few conversations circulating, and from what I understand 1e5 attoFIL, is too low, maybe @Kubuxu can chip in. There have been suggestions to bump the alert to the 2 nanoFIL or 3 nanoFIL levels.

---

I liked the idea to also have some kind of rate of change alert, but I imagine this is more difficult to get right.

**Comment by frrist** [comment]
@placer14 to write up an issue for follow-ons needed to complete this work and close this issue.

**Comment by olizilla** [comment]
I bumped the threshold up to 3 nanoFIL in https://protocollabs.grafana.net/d/yHSVex5Mz/sentinel-monitoring-eks?viewPanel=31&orgId=1&refresh=1m

**Comment by placer14** [comment]
We have a threshold set but are tweaking this value in realtime. Will revisit this later if needed.
