### ISSUE TITLE
Review all metrics in Mainnet Analysis dashboard

### ISSUE THREAD

**Issue by birdychang** [filecoin-project/sentinel#232]
Review all metrics to ensure the data makes sense. Fix sql queries if necessary. Remove outdated or irrelevant metrics.

https://protocollabs.grafana.net/d/m1P_m92Gz/mainnet-analysis?var-DB=Sentinel%20Lily%20%28Mainnet%20Production%29&var-bucket_size=1h&orgId=1&from=now-24h&to=now

**Comment by Terryhung** [comment]
### Refer to the dashboards of other companies and teams to enrich our own dashboard.
1. https://dashboard.starboard.ventures/market-deals

**Comment by birdychang** [comment]
@Terryhung is this done?
