### ISSUE TITLE
Provide message return value data

### ISSUE THREAD

**Issue by birdychang** [filecoin-project/sentinel#244]
It was [reported](https://filecoinproject.slack.com/archives/C0174P5M11T/p1690358446305049) that there's no message return value in our datasets.

Although there's an [effort](https://github.com/filecoin-project/lily/pull/1140/commits/1e6f1e34941dc14d3aa6474d1f517b1a1883bdd2) previously to extract raw return value data, the task was never executed and the design is not user friendly.

After some internal discussions, the team decided to add both raw and parsed return value to the `receipts` table. 

Tasks:
- [x] update Lily code to include new columns (https://github.com/filecoin-project/lily/pull/1248)
- [x] cut a new release and deploy to production (https://github.com/filecoin-project/lily/pull/1250, [v0.17.0](https://hub.docker.com/layers/filecoin/lily/v0.17.0/images/sha256-d384697a18dda2425455b88bdef3c08935f5388c74d7aa135bd26d392860e539?context=explore))
- [x] verify new timescaleDB data 
- [x] make schema changes in BigQuery
- [x] test with one snapshot and verify backfilled BigQuery data
- [x] backfill `receipts` table in BigQuery since 3/14
- [x] backfill `receipts` table in BigQuery from 2023/01/01 to 2023/03/14 
- [x] backfill `receipts` table in BigQuery from 2022/01/01 to 2022/12/31

**Comment by charliealgernon** [comment]
Following up from this [Slack thread](https://filecoinproject.slack.com/archives/C0174P5M11T/p1690358446305049). Are we still on track to complete the backfill in a week or so (given that it was scoped for 2 weeks a week ago)?

**Comment by Terryhung** [comment]
hi @charliealgernon,
Since 3/14, we've backfilled the receipt `return` and` return_parsed` data.

**Comment by charliealgernon** [comment]
What about before 3/14?

**Comment by Terryhung** [comment]
@charliealgernon This week, we will be backfilling data from January 1, 2023, to March 14, 2023. Subsequently, we plan to backfill the data for the year 2022 in the upcoming weeks.

**Comment by charliealgernon** [comment]
@Terryhung Thanks for the update. Good to hear that by EOW we'll have all of 2023 (ytd). Do you have an ETA for 2022?

**Comment by Terryhung** [comment]
@charliealgernon FYI, the data from 2022 is available for use now!
