### ISSUE TITLE
ID Addresses for actors are not deterministic through reorgs

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel#45]
Chainwatch schema currently uses actor ID addresses (t0) to uniquely identify actors on-chain. ID addresses are exposed to inconsistencies through reorgs changing the order of applied messages (through inclusions/removals of new messages). This is an issue to reconsider capture of actors to include Actor Addresses (t2) which are unique to sender, nonce, method and should be deterministic through most any reorg. (A complex edge case where the sender RBF the original message with a new message would cause the t2 to be different through a reorg due to the nonce changing on the new message.)

**Comment by frrist** [comment]
This is no longer an issues as Visor now includes a state root with the address pair. This means addresses can be deterministically identified by the state root they were valid at.
