### ISSUE TITLE
Chainwatch can connect via multiaddr and token

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel#47]
Chainwatch requires access to the filesystem to find the API endpoint and token. Instead of requiring disk access, these values should be alternately configurable instead of requiring `LOTUS_PATH` or `--repo` flags.

## Acceptance Criteria
- [ ] On `run` subcommand, accept `--api` flag or `LOTUS_API_INFO` and `FULLNODE_API_INFO` env var as runtime option (format follows `./lotus auth api-info --perm read` as `<TOKEN>:<MULTIADDR>`.)
- [ ] On `run` subcommand, prefer `--api` flag values over values sourced by filesystem, if available. Error as usual w insufficient creds.

**Comment by frrist** [comment]
visor accepts an API token as well, closing. (Also not sure why closing #3337 didn't' close this too)
