### ISSUE TITLE
Dashboard: Consecutive Null Rounds by Host

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel#73]

**Comment by placer14** [comment]
@lanzafame In case you hadn't already figured this out, it is the block CID and is just poorly named: https://github.com/filecoin-project/sentinel-drone/blob/master/plugins/inputs/lotus/lotus.go#L415

**Comment by placer14** [comment]
I removed the "by Host" requirement as it doesn't make sense to communicate many perspectives of the same set of null rounds. Probably more interesting are deviations in null round spans between hosts...but not so obvious how to represent this yet. So here are the top 100 longest trends of null rounds and the most recent trends of null rounds seen on-chain. 

http://compute0-large.na.kittyhawk.wtf:3000/d/sentinel_v0_2/sentinel-v0-2-space-race?orgId=1&refresh=15m
![Screen Shot 2020-09-17 at 4.03.46 PM.png](https://images.zenhubusercontent.com/595a62c561b4ca3b0a73107a/d3a266e8-274a-4204-8df0-f53f2dabde31)

**Comment by frrist** [comment]
Looks to be done, closing.
