### ISSUE TITLE
Alert: >5 Consecutive Null Rounds

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel#74]

**Comment by placer14** [comment]
Similar to the concern raised at https://github.com/filecoin-project/sentinel/issues/73#issuecomment-694470354, I have removed the "by Host" requirement on this alert.

**Comment by placer14** [comment]
Okay, so the above alert will trigger when there's a long round of null tipsets. Either more than 5 long or when there are more than 100 total over the past 24 hours. We can't know if a round of null tipsets from latest block is actually a network outage or a long line of null tipsets (because secret election) so this alert should cover both cases. We can dial these in as needed.

**Comment by placer14** [comment]
Example of alerting panel...showing a leading round of nulls (due to node being off).
<img width="447" alt="Screen Shot 2020-09-18 at 4 13 19 PM" src="https://user-images.githubusercontent.com/305332/93641233-f1482000-f9c9-11ea-8376-cb83535740b4.png">

Resulting alert.
<img width="547" alt="Screen Shot 2020-09-18 at 4 13 30 PM" src="https://user-images.githubusercontent.com/305332/93641234-f1e0b680-f9c9-11ea-9b6c-1494554adfda.png">

**Comment by frrist** [comment]
Assuming this can be closed as its in the done column of the sentinel zenboard.
