### ISSUE TITLE
Notification: <80% Raw Byte Power Velocity rate change over prior 1 wk window

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel#84]

**Comment by lanzafame** [comment]
This has been added in the main sentinel dashboard, can't test as it grafana alerts can only go back 48h in the data that they query and sentinel isn't that up-to-date with data.

**Comment by iand** [comment]
Changing to notification. Alerts are reserved for actionable behaviour by ops team. Notifications indicate issues that are of interest to product and engineering but not immediately actionable.
