### ISSUE TITLE
Notification: <75% PreCommit -> ProveCommit Success/Total over prior 1wk

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel#86]
Requires parsed messages of the Pre/ProveCommit messages per Miner and showing these success/failures over time. Then aggregating all successes/failures over prior 1wk period.

**Comment by iand** [comment]
Changing to notification. Alerts are reserved for actionable behaviour by ops team. Notifications indicate issues that are of interest to product and engineering but not immediately actionable.
